// src/config/categoriasTienda.js
// Definición central de las categorías del catálogo de la tienda.
// Fuente de la clasificación: (1) códigos ATC de las moléculas del producto
// (vía producto_moleculas -> moleculas_referencias.atc_id -> atc_clasificaciones),
// (2) keywords de respaldo sobre molecula/nombre_comercial, (3) formas
// farmacéuticas, (4) varia el `linea`/INYECTABLE hacia 'hospitalario'.
// El backfill vive en scripts/clasificar-categorias.mjs (idempotente).

export const CATEGORIAS_TIENDA = [
  {
    id: 'analgesicos',
    nombre: 'Analgésicos y antiinflamatorios',
    icono: 'Pill',
    atc: ['N02', 'M01', 'M02', 'M03'],
    keywords: [
      'acetaminof', 'paracetamol', 'ibuprofeno', 'naproxeno', 'ketorolac',
      'ketorolaco', 'diclofenaco', 'ketoprofeno', 'meloxicam', 'piroxicam',
      'dipirona', 'metamizol', 'tramadol', 'morfina', 'oxicodona', 'hidrocodona',
      'codeina', 'aspirina', 'acido acetilsalicilico', 'salicilato', 'indometacina',
      'etoricoxib', 'celecoxib', 'nimesulida', 'dexketoprofeno', 'naproxeno',
      'flurbiprofeno', 'tenoxicam', 'acetaminofen', 'gel de diclofenaco',
      'capalcina', 'capsaicina', 'mentol', 'tiocolchicosido', 'ciclobenzaprina',
      'orfenadrina', 'eperisona', 'tolperisona',
    ],
  },
  {
    id: 'cardiovascular',
    nombre: 'Cardiovascular',
    icono: 'HeartPulse',
    atc: ['C', 'B01'],
    keywords: [
      'enalapril', 'losartan', 'valsartan', 'irbesartan', 'candesartan',
      'telmisartan', 'olmesartan', 'eprosartan', 'atenolol', 'metoprolol',
      'propranolol', 'bisoprolol', 'carvedilol', 'nebivolol', 'amlodipino',
      'nifedipino', 'felodipino', 'lerkanidipino', 'levamlodipino', 'nicardipino',
      'hidroclorotiazida', 'clortalidona', 'furosemida', 'torsemida', 'espironolactona',
      'amilorida', 'triamtereno', 'digoxina', 'amiodarona', 'nitroglicerina',
      'isosorbida', 'mononitrato', 'dinitrato', 'rivaroxaban', 'apixaban', 'edoxaban',
      'clopidogrel', 'warfarina', 'acenocumarol', 'heparina', 'enoxaparina',
      'dabigatran', 'ticagrelor', 'prasugrel', 'atorvastatina', 'simvastatina',
      'rosuvastatina', 'pravastatina', 'fluvastatina', 'lovastatina', 'ezetimiba',
      'fenofibrato', 'gemfibrozil', 'nicotina parche', 'trimetazidina', 'ranolazina',
      'ivabradina', 'diltiazem', 'verapamilo', 'nifedipina', 'alprenolol',
      'dobutamina', 'dopamina', 'norepinefrina', 'vasopresina',
    ],
  },
  {
    id: 'antidiabeticos',
    nombre: 'Antidiabéticos',
    icono: 'Activity',
    atc: ['A10'],
    keywords: [
      'metformina', 'glibenclamida', 'glimepirida', 'gliclazida', 'glipizida',
      'pioglitazona', 'rosiglitazona', 'sitagliptina', 'linagliptina', 'saxagliptina',
      'vildagliptina', 'empagliflozina', 'dapagliflozina', 'canagliflozina',
      'insulina', 'acarbosa', 'miglitol', 'liraglutida', 'semaglutida', 'dulaglutida',
      'exenatida', 'lixisenatida', 'glucosa tiras', 'glucagón', 'monitoreo glucosa',
    ],
  },
  {
    id: 'digestivo',
    nombre: 'Estómago y digestión',
    icono: 'Utensils',
    atc: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08', 'A09'],
    keywords: [
      'omeprazol', 'lansoprazol', 'pantoprazol', 'esomeprazol', 'rabeprazol',
      'ranitidina', 'famotidina', 'cimetidina', 'sucralfato', 'bismuto',
      'domperidona', 'metoclopramida', 'ondansetron', 'granisetron', 'palonosetron',
      'hioscina', 'butilhioscina', 'bromuro de hioscina', 'loperamida', 'smectita',
      'diosmectita', 'racadotril', 'hidralazina laxante', 'lactulosa', 'bisacodilo',
      'picosulfato', 'polietilenglicol', 'psyllium', 'plantago', 'simeticona',
      'dimeticona', 'lubiprostona', 'prucaloprida', 'trimebutina', 'mebeverina',
      'pinaverio', 'pectina', 'caolin', 'carbón activado', 'bicarbonato',
      'antiacido', 'flor de azufre', 'pancreatina', 'enzimas', 'dimenhidrinato',
      'meclizina', 'escopolamina',
    ],
  },
  {
    id: 'vitaminas',
    nombre: 'Vitaminas y suplementos',
    icono: 'Citrus',
    atc: ['A11', 'A12', 'B03', 'B06', 'B05', 'V', 'A14'],
    keywords: [
      'vitamin', 'vitamina a', 'vitamina b', 'vitamina c', 'vitamina d', 'vitamina e',
      'vitamina k', 'acido folico', 'folio', 'cianocobalamina', 'hidroxocobalamina',
      'tiamina', 'riboflavina', 'niacina', 'piridoxina', 'biotina', 'pantotenico',
      'ascorbico', 'colecalciferol', 'ergocalciferol', 'tocoferol', 'fitomenadiona',
      'multivitamina', 'multivitaminico', 'ferroso', 'ferrico', 'hierro', 'sacarina ferrica',
      'sacarato de hierro', 'carbonato de calcio', 'calcio', 'gluconato de calcio',
      'magnesio', 'oxido de magnesio', 'zinc', 'selenio', 'cromo', 'potasio',
      'omega', 'omega-3', 'dha', 'epa', 'proteina', 'aminoacidos', 'creatina',
      'colageno', 'suplemento',
    ],
  },
  {
    id: 'nervioso',
    nombre: 'Sistema nervioso',
    icono: 'Brain',
    atc: ['N03', 'N05', 'N06', 'N07'],
    keywords: [
      'sertralina', 'fluoxetina', 'escitalopram', 'paroxetina', 'citalopram',
      'fluvoxamina', 'venlafaxina', 'duloxetina', 'desvenlafaxina', 'mirtazapina',
      'bupropion', 'trazodona', 'nefazodona', 'clonazepam', 'diazepam', 'alprazolam',
      'lorazepam', 'bromazepam', 'clobazam', 'clordiazepoxido', 'nitrazepam', 'flunitrazepam',
      'midazolam', 'zolpidem', 'zopiclona', 'eszopiclona', 'melatonina', 'quetiapina',
      'risperidona', 'olanzapina', 'aripiprazol', 'lurasidona', 'paliperidona', 'clozapina',
      'haloperidol', 'amisulprida', 'lamotrigina', 'carbamazepina', 'oxcarbazepina',
      'valproico', 'valproato', 'levetiracetam', 'topiramato', 'gabapentina', 'pregabalina',
      'fenobarbital', 'fenitoina', 'etosuximida', 'vigabatrina', 'lacosamida', 'perampanel',
      'buspirona', 'litio', 'donepezilo', 'rivastigmina', 'memantina', 'galantamina',
      'metilfenidato', 'atomoxetina', 'lisdexanfetamina', 'nortriptilina', 'imipramina',
      'amitriptilina', 'clomipramina', 'maprotilina', 'ansi', 'ansiolitico', 'antidepresivo',
      'antiepileptico', 'anticonvulsivante', 'parkinson', 'levodopa', 'carbidopa',
      'biperideno', 'pramipexol', 'ropinirol',
    ],
  },
  {
    id: 'alergia',
    nombre: 'Alergia',
    icono: 'Flower2',
    atc: ['R06', 'D04'],
    keywords: [
      'loratadina', 'cetirizina', 'desloratadina', 'levocetirizina', 'fexofenadina',
      'ebastina', 'bilastina', 'rupatadina', 'difenhidramina', 'clorfeniramina',
      'clorfenamina', 'dexclorfeniramina', 'prometazina', 'hidroxicina', 'doxilamina',
      'ketotifeno', 'antihistaminico', 'cromoglicato', 'cromoglicico', 'azelastina',
      'levocabastina', 'olopatadina', 'alergia', 'antialergico',
    ],
  },
  {
    id: 'respiratorio',
    nombre: 'Respiratorio',
    icono: 'Wind',
    atc: ['R01', 'R03', 'R07'],
    keywords: [
      'montelukast', 'zafirlukast', 'salbutamol', 'albuterol', 'salmeterol',
      'formoterol', 'vilanterol', 'indacaterol', 'olodaterol', 'beclometasona',
      'fluticasona', 'budesonida', 'ciclesonida', 'mometasona', 'ipratropio',
      'tiotropio', 'umedidinio', 'teofilina', 'aminofilina', 'doxofilina',
      'ambroxol', 'acetilcisteina', 'carbocisteina', 'bromhexina', 'mucolitico',
      'expectorante', 'xilometazolina', 'oximetazolina', 'oclometazolina',
      'fenilefrina', 'fenilefrina nasal', 'cromoglicato', 'fenspirida',
      'asma', 'nebulizacion', 'solucion salina isotonica',
      'bromuro de ipratropio', 'palivizumab',
    ],
  },
  {
    id: 'tos-resfriado',
    nombre: 'Tos, resfriado y garganta',
    icono: 'Thermometer',
    atc: ['R02', 'R05'],
    keywords: [
      'dextrometorfano', 'guafenesina', 'noscapina', 'cloperastina', 'levodropropizina',
      'pseudoefedrina', 'fenilefrina', 'clorfeniramina', 'paracetamol gripe',
      'gripe', 'resfriado', 'catarro', 'cetilpiridinio', 'bencidamina',
      'ambroxol', 'flurbiprofeno', 'antigripal', 'bronquiolitis', 'faringeo',
      'garganta', 'rinitis', 'aerogrip', 'duogrip', 'antitussi', 'antitusigeno',
      'expectorante', 'mucolitico', 'jarabe para la tos', 'tos', 'tos seca', 'noche',
    ],
  },
  {
    id: 'piel',
    nombre: 'Cuidado de la piel',
    icono: 'HandHeart',
    atc: ['D', 'A01'],
    formas: ['CREMA', 'UNGUENTO', 'POMADA', 'LOCION', 'SOLUCION TOPICA', 'GEL', 'JABON', 'SHAMPOO', 'CHAMPU', 'EMULSION', 'BARRA'],
    keywords: [
      'clotrimazol', 'miconazol', 'ketoconazol', 'econazol', 'sertaconazol', 'tioconazol',
      'terbinafina', 'nistatina', 'ciclopirox', 'amorolfina', 'betametasona', 'hidrocortisona',
      'dexametasona topica', 'prednicarbato', 'clobetasol', 'mometasona', 'fluticasona topica',
      'tacrolimus', 'pimecrolimus', 'calamina', 'oxido de zinc', 'acido salicilico',
      'acido salicílico', 'peroxido de benzoilo', 'adapaleno', 'isotretinoina', 'tretinoina',
      'bencilo', 'urea', 'emoliente', 'vaselina', 'lanolina', 'glicerina', 'quemadura',
      'cicatriz', 'pomada', 'unguento', 'sarpullido', 'dermatitis', 'psoriasis', 'eczema',
      'acne', 'escabicida', 'lindano', 'permetrina', 'azufre', 'alquitrán', 'acidovir',
      'aciclovir topico', 'penciclovir', 'mupirocina', 'fucidico', 'neomicina', 'bacitracina',
      'sulfadiazina de plata', 'nitrofurazona', 'hidroquinona', 'tretinoina', 'cinamato',
      'bloqueador solar', 'protector solar', 'crema', 'hialuronico', 'acido hialuronico',
      'retinol', 'niacinamida', 'vitamina e topica',
    ],
  },
  {
    id: 'ojos-oidos',
    nombre: 'Ojos y oídos',
    icono: 'Eye',
    atc: ['S01', 'S02', 'S03'],
    formas: ['SOLUCION OFTALMICA', 'SOLUCION OTICA'],
    keywords: [
      'ofloxacina', 'ofloxacino', 'ciprofloxacino', 'moxifloxacino', 'levofloxacino',
      'tobramicina', 'gentamicina', 'neomicina', 'polimixina', 'bacitracina',
      'timolol', 'latanoprost', 'bimatoprost', 'travoprost', 'dorzolamida',
      'brinzolamida', 'brimonidina', 'pilocarpina', 'artificial', 'lagrima',
      'lágrimas', 'lagrimas', 'sulfacetamida', 'prednisolona ofta', 'dexametasona',
      'fluoresceina', 'trifluridina', 'antihistaminico oftalmico', 'oftalmico',
      'otico', 'gotas otologicas', 'ciprofloxacina otica', 'corticoide otico',
      'fotofobia', 'ojos', 'oídos', 'conjuntivitis', 'otitis',
    ],
  },
  {
    id: 'antiinfecciosos',
    nombre: 'Antiinfecciosos',
    icono: 'ShieldPlus',
    atc: ['J', 'P01', 'D08'],
    keywords: [
      'amoxicilina', 'ampicilina', 'penicilina', 'azitromicina', 'claritromicina',
      'eritromicina', 'cefalexina', 'cefuroxima', 'ceftriaxona', 'cefazolina',
      'cefixima', 'cefpodoxima', 'ceftazidima', 'cefotaxima', 'ciprofloxacino', 'ciprofloxacina',
      'levofloxacino', 'levofloxacina', 'ofloxacino', 'ofloxacina', 'moxifloxacino', 'moxifloxacina',
      'norfloxacino', 'norfloxacina', 'tetraciclina',
      'doxiciclina', 'minociclina', 'metronidazol', 'tinidazol', 'clindamicina',
      'vancomicina', 'linezolid', 'nitrofurantoina', 'trimetoprim', 'sulfametoxazol',
      'cotrimoxazol', 'sulfonamida', 'fluconazol', 'itraconazol', 'ketoconazol',
      'voriconazol', 'posaconazol', 'anfotericina', 'micafungina', 'caspofungina',
      'nistatina', 'terbinafina', 'grisofulvina', 'aciclovir', 'valaciclovir',
      'famciclovir', 'gansiklovir', 'valgansiklovir', 'oseltamivir', 'zanamivir',
      'ribavirina', 'cloranfenicol', 'gentamicina', 'amikacina', 'tobramicina',
      'netilmicina', 'fosfomicina', 'meropenem', 'imipenem', 'ertapenem', 'aztreonam',
      'rifampicina', 'isoniazida', 'etambutol', 'pirazinamida', 'dapsona',
      'clofazimina', 'antibiotico', 'antifungico', 'antiviral',
      'higienico', 'antiséptico', 'antisep', 'alcohol', 'povidona', 'yodo',
      'povidona yodada', 'clorhexidina', 'infeccion', 'infecciones',
    ],
  },
  {
    id: 'antiparasitarios',
    nombre: 'Antiparasitarios',
    icono: 'Bug',
    atc: ['P02', 'P03', 'P01'],
    keywords: [
      'albendazol', 'mebendazol', 'pirantel', 'pamoato de pirantel', 'nitazoxanida',
      'ivermectina', 'secnidazol', 'ornidazol', 'cloroquina', 'hidroxicloroquina',
      'primaquina', 'praziquantel', 'niclosamida', 'tiabendazol', 'pentamidina',
      'atovacuona', 'proguanil', 'artemeter', 'lumefantrina', 'antiparasitario',
      'parasitos', 'parasitosis', 'amebiasis', 'giardiasis', 'oxiuros', 'lombrices',
    ],
  },
  {
    id: 'salud-femenina',
    nombre: 'Salud femenina',
    icono: 'Venus',
    atc: ['G01', 'G02', 'G03'],
    formas: ['OVULOS', 'CREMA VAGINAL', 'TABLETA VAGINAL', 'PESARIO'],
    keywords: [
      'clotrimazol', 'miconazol', 'tioconazol', 'butoconazol', 'econazol',
      'nistatina', 'metronidazol', 'tinidazol', 'norgestrel', 'etinilestradiol',
      'levonorgestrel', 'medroxiprogesterona', 'progesterona', 'estradiol',
      'estrogeno', 'ciproterona', 'dienogest', 'drospirenona', 'desogestrel',
      'gestodeno', 'clormadinona', 'vaginal', 'ovulo', 'flujo', 'candidiasis',
      'irritacion vaginal', 'vaginosis', 'antibiotico vaginal', 'antimicotico vaginal',
      'climaterio', 'menopausia', 'menstruacion', 'prenatal', 'embarazo', 'lactancia',
      'anticonceptivo', 'postday', 'emergencia anticonceptiva', 'toalla',
    ],
  },
  {
    id: 'salud-masculina',
    nombre: 'Salud masculina y urológico',
    icono: 'Mars',
    atc: ['G04'],
    keywords: [
      'tadalafilo', 'tadalafil', 'sildenafil', 'sildenafilo', 'vardenafil', 'avanafil',
      'dutasterida', 'finasterida', 'silodosina', 'tamsulosina', 'alfuzosina',
      'doxazosina', 'terazosina', 'oxibutinina', 'tolterodina', 'solifenacina',
      'fesoterodina', 'darifenacina', 'mirabegron', 'urologico', 'prostata',
      'disfuncion erectil', 'ereccion', 'vejiga', 'incontinencia', 'uretral', 'renal',
      'litiasis', 'calculo renal', 'cistitis', 'sonda urinaria', 'uroginecologia',
    ],
  },
  {
    id: 'hospitalario',
    nombre: 'Hospitalario e insumos',
    icono: 'Cross',
    atc: [],
    keywords: [
      'jeringa', 'aguja', 'gasas', 'gasa', 'algodon', 'guante', 'sonda', 'cateter',
      'sutura', 'venda', 'aposito', 'esparadrapo', 'tela adhesiva', 'mascarilla',
      'barbijo', 'cubre', 'bata', 'gotero', 'tensiometro', 'termometro', 'glucometro',
      'suero', 'solucion salina', 'cloruro de sodio', 'cloruro de potasio', 'dextrosa',
      'agua destilada', 'electrolitos', 'bolsa de', 'equipo de infusion', 'infusion',
      'bata quirurgica', 'campo quirurgico', 'delantal', 'torniquete', 'lanceta',
      'tiras reactivas', 'test de', 'prueba de embarazo', 'bajada de', 'hemoclamp',
      'micropor', 'banda elastica', 'tijera', 'pincel', 'espatula', 'depresor',
      'abatelenguas', 'papel para', 'toalla de', 'toallas', 'pampers', 'panal',
      'contenedor', 'orinal', 'cuña', 'férula', 'abrazadera', 'colostomia',
      'ostomia', 'bolsa de ostomia',
    ],
  },
];

export const CATEGORIA_POR_ID = Object.fromEntries(
  CATEGORIAS_TIENDA.map((c) => [c.id, c])
);

export default CATEGORIAS_TIENDA;