-- 014_productos_catalogo.sql
-- Catálogo público de consulta basado en el CSV del INHRR (Instituto Nacional
-- de Higiene "Rafael Rangel"). Separado del inventario real (tabla productos).
--
-- Incluye:
--   productos_catalogo  -> catálogo de consulta (7,416 registros tras purga)
--   catalogo_moleculas  -> bridge N:N hacia moleculas_referencias (CIMA)
--   v_catalogo_productos-> vista de lectura con moléculas + ATC agregados
--   catalogo_listar()   -> RPC de búsqueda paginada con filtros
--   catalogo_producto() -> RPC de ficha por SKU
--   catalogo_metadata() -> RPC con valores distintos para los filtros
--
-- La purga/categoría/SKU/matching de moléculas lo hace el script DuckDB
-- scripts/importar-catalogo.mjs. ESTE ARCHIVO solo crea el esquema.
-- Después de ejecutarlo, cargar los datos con scripts/cargar-catalogo.sql
-- (psql, igual que la migración 013).

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- =========================================================
-- 1) productos_catalogo
-- =========================================================
CREATE TABLE IF NOT EXISTS productos_catalogo (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku                text NOT NULL UNIQUE,           -- {CATEGORIA}{numero registro} (ME45256, HO931B)
  ef                 text NOT NULL UNIQUE,           -- identificador INHRR original (E.F.45.256)
  sort_id            bigint,                          -- número del registro sanitario
  nombre             text NOT NULL,
  forma              text,                            -- forma farmacéutica derivada del nombre
  categoria          text NOT NULL CHECK (categoria IN ('ME', 'HO', 'MM', 'MI')),
  principio_activo   text,                            -- tal cual lo trae el INHRR (puede ser compuesto)
  laboratorio        text,                            -- patrocinante, o representante si no hay
  representante      text,
  rif_representante  text,
  patrocinante       text,
  fabricante         text,
  fecha_aprobado     date,
  fecha_vigencia     date,                            -- vencimiento del registro sanitario (NULL = por revisar)
  fecha_cancelado    date,
  activo             boolean NOT NULL DEFAULT true,   -- false cuando el registro se cancela en una re-importación
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_catalogo_nombre_trgm      ON productos_catalogo USING gin (nombre gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_catalogo_lab_trgm         ON productos_catalogo USING gin (laboratorio gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_catalogo_categoria        ON productos_catalogo (categoria);
CREATE INDEX IF NOT EXISTS idx_catalogo_forma            ON productos_catalogo (forma);

-- =========================================================
-- 2) catalogo_moleculas (bridge N:N)
-- =========================================================
CREATE TABLE IF NOT EXISTS catalogo_moleculas (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_catalogo_id  bigint NOT NULL REFERENCES productos_catalogo(id) ON DELETE CASCADE,
  molecula_id           bigint NOT NULL REFERENCES moleculas_referencias(id),
  score                 numeric(5, 4),               -- confianza del match fuzzy (0.90+ = automático)
  created_at            timestamptz NOT NULL DEFAULT now(),
  UNIQUE (producto_catalogo_id, molecula_id)
);

CREATE INDEX IF NOT EXISTS idx_catalogo_mol_producto   ON catalogo_moleculas (producto_catalogo_id);
CREATE INDEX IF NOT EXISTS idx_catalogo_mol_molecula   ON catalogo_moleculas (molecula_id);

-- =========================================================
-- 3) RLS: lectura pública (el catálogo es de solo consulta)
-- =========================================================
ALTER TABLE productos_catalogo ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalogo_moleculas ENABLE ROW LEVEL SECURITY;

CREATE POLICY catalogo_productos_publico ON productos_catalogo FOR SELECT USING (true);
CREATE POLICY catalogo_moleculas_publico  ON catalogo_moleculas  FOR SELECT USING (true);

-- =========================================================
-- 4) Vista de lectura con moléculas + ATC agregados
-- =========================================================
CREATE OR REPLACE VIEW v_catalogo_productos AS
SELECT
  p.id,
  p.sku,
  p.ef,
  p.nombre,
  p.forma,
  p.categoria,
  p.laboratorio,
  p.fabricante,
  p.principio_activo,
  p.fecha_aprobado,
  p.fecha_vigencia,
  p.fecha_cancelado,
  p.activo,
  COALESCE((
    SELECT jsonb_agg(jsonb_build_object('id', m.id, 'nombre', m.nombre, 'atc', a.codigo) ORDER BY m.nombre)
    FROM catalogo_moleculas cm
    JOIN moleculas_referencias m ON m.id = cm.molecula_id
    LEFT JOIN atc_clasificaciones a ON a.id = m.atc_id
    WHERE cm.producto_catalogo_id = p.id
  ), '[]'::jsonb) AS moleculas
FROM productos_catalogo p;

-- =========================================================
-- 5) RPC de búsqueda paginada con filtros
--    GET /catalogo?q=&categoria=&forma=&laboratorio=&molecula=&page=&page_size=
-- =========================================================
CREATE OR REPLACE FUNCTION public.catalogo_listar(
  p_q          text DEFAULT NULL,
  p_categoria  text DEFAULT NULL,
  p_forma      text DEFAULT NULL,
  p_laboratorio text DEFAULT NULL,
  p_molecula   text DEFAULT NULL,
  p_page       integer DEFAULT 1,
  p_page_size  integer DEFAULT 20
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_page   integer;
  v_size   integer;
  v_offset integer;
  v_total  bigint;
  v_rows   jsonb;
BEGIN
  v_page   := GREATEST(COALESCE(p_page, 1), 1);
  v_size   := LEAST(GREATEST(COALESCE(p_page_size, 20), 1), 100);
  v_offset := (v_page - 1) * v_size;

  SELECT count(*) INTO v_total
  FROM v_catalogo_productos v
  WHERE (NULLIF(p_q, '') IS NULL OR v.nombre ILIKE '%' || p_q || '%')
    AND (p_categoria IS NULL OR v.categoria = p_categoria)
    AND (p_forma IS NULL OR v.forma = p_forma)
    AND (NULLIF(p_laboratorio, '') IS NULL OR v.laboratorio ILIKE '%' || p_laboratorio || '%')
    AND (NULLIF(p_molecula, '') IS NULL OR v.id IN (
          SELECT cm.producto_catalogo_id
          FROM catalogo_moleculas cm
          JOIN moleculas_referencias m ON m.id = cm.molecula_id
          WHERE m.nombre ILIKE '%' || p_molecula || '%'))
    AND v.activo;

  SELECT COALESCE(jsonb_agg(j ORDER BY (j->>'nombre')), '[]'::jsonb) INTO v_rows
  FROM (
    SELECT to_jsonb(v.*) AS j
    FROM v_catalogo_productos v
    WHERE (NULLIF(p_q, '') IS NULL OR v.nombre ILIKE '%' || p_q || '%')
      AND (p_categoria IS NULL OR v.categoria = p_categoria)
      AND (p_forma IS NULL OR v.forma = p_forma)
      AND (NULLIF(p_laboratorio, '') IS NULL OR v.laboratorio ILIKE '%' || p_laboratorio || '%')
      AND (NULLIF(p_molecula, '') IS NULL OR v.id IN (
            SELECT cm.producto_catalogo_id
            FROM catalogo_moleculas cm
            JOIN moleculas_referencias m ON m.id = cm.molecula_id
            WHERE m.nombre ILIKE '%' || p_molecula || '%'))
      AND v.activo
    ORDER BY v.nombre
    LIMIT v_size OFFSET v_offset
  ) x;

  RETURN jsonb_build_object(
    'rows',      COALESCE(v_rows, '[]'::jsonb),
    'total',     v_total,
    'page',      v_page,
    'page_size', v_size
  );
END;
$$;

-- =========================================================
-- 6) RPC de ficha por SKU
--    GET /catalogo/:sku
-- =========================================================
CREATE OR REPLACE FUNCTION public.catalogo_producto(p_sku text)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result jsonb;
BEGIN
  SELECT to_jsonb(v.*) INTO v_result
  FROM v_catalogo_productos v
  WHERE v.sku = p_sku;

  RETURN v_result;
END;
$$;

-- =========================================================
-- 7) RPC con valores distintos para los filtros del frontend
-- =========================================================
CREATE OR REPLACE FUNCTION public.catalogo_metadata()
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_categorias  jsonb;
  v_formas      jsonb;
  v_laboratorios jsonb;
  v_total       bigint;
BEGIN
  SELECT COALESCE(jsonb_agg(categoria ORDER BY categoria), '[]'::jsonb)
    INTO v_categorias
  FROM (SELECT DISTINCT categoria FROM productos_catalogo WHERE activo) t;

  SELECT COALESCE(jsonb_agg(forma ORDER BY forma), '[]'::jsonb)
    INTO v_formas
  FROM (SELECT DISTINCT forma FROM productos_catalogo WHERE activo AND forma IS NOT NULL) t;

  SELECT COALESCE(jsonb_agg(laboratorio ORDER BY laboratorio), '[]'::jsonb)
    INTO v_laboratorios
  FROM (SELECT DISTINCT laboratorio FROM productos_catalogo WHERE activo AND laboratorio IS NOT NULL) t;

  SELECT count(*) INTO v_total FROM productos_catalogo WHERE activo;

  RETURN jsonb_build_object(
    'categorias',   v_categorias,
    'formas',       v_formas,
    'laboratorios', v_laboratorios,
    'total',        v_total
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.catalogo_listar(text, text, text, text, text, integer, integer) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.catalogo_producto(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.catalogo_metadata() TO anon, authenticated;