import pg from "pg"; import dotenv from "dotenv"; import fs from "fs";
dotenv.config();
const { Client } = pg;
const c = new Client({ host: process.env.SUPABASE_DB_HOST, port: process.env.SUPABASE_DB_PORT||5432, database: process.env.SUPABASE_DB_NAME||"postgres", user: process.env.SUPABASE_DB_USER, password: process.env.SUPABASE_DB_PASSWORD, ssl: { rejectUnauthorized:false } });
await c.connect();
const r = await c.query(`select id, nombre_comercial, precio_usd, costo_usd, disponible, activo, visible_catalogo from productos where id = 38890`);
console.log("ORIGINAL:", JSON.stringify(r.rows[0]));
fs.writeFileSync("C:\\Users\\Usuario\\AppData\\Local\\Temp\\opencode\\qa_producto_original.json", JSON.stringify(r.rows[0]));
const u = await c.query(`update productos set precio_usd = null, disponible = false where id = 38890 returning id, precio_usd, disponible`);
console.log("DESPUBLICADO:", JSON.stringify(u.rows[0]));
await c.end();
