import pg from "pg"; import dotenv from "dotenv"; dotenv.config();
const { Client } = pg;
const c = new Client({ host: process.env.SUPABASE_DB_HOST, port: process.env.SUPABASE_DB_PORT||5432, database: process.env.SUPABASE_DB_NAME||"postgres", user: process.env.SUPABASE_DB_USER, password: process.env.SUPABASE_DB_PASSWORD, ssl: { rejectUnauthorized:false } });
await c.connect();
const req = await c.query(`select id, usuario_id, estado from requerimientos where id=3`);
console.log("requerimiento 3:", JSON.stringify(req.rows[0]));
const it = await c.query(`select id, estado_item, producto_id, nombre_solicitado from requerimiento_items where requerimiento_id=3`);
console.log("item:", JSON.stringify(it.rows[0]));
const pr = await c.query(`select id, nombre_comercial, precio_usd, disponible, visible_catalogo, sku, linea, forma, activo from productos where id = $1`, [it.rows[0].producto_id]);
console.log("producto creado por responder:", JSON.stringify(pr.rows[0]));
await c.end();
