import pg from "pg"; import dotenv from "dotenv"; dotenv.config();
const { Client } = pg;
const c = new Client({ host: process.env.SUPABASE_DB_HOST, port: process.env.SUPABASE_DB_PORT||5432, database: process.env.SUPABASE_DB_NAME||"postgres", user: process.env.SUPABASE_DB_USER, password: process.env.SUPABASE_DB_PASSWORD, ssl: { rejectUnauthorized:false } });
await c.connect();
const itemIds = (await c.query(`select id from requerimiento_items where requerimiento_id in (2,3)`)).rows.map(r=>r.id);
console.log("items a borrar:", itemIds);
if (itemIds.length) await c.query(`delete from requerimiento_items where id = any($1)`, [itemIds]);
const r = await c.query(`delete from requerimientos where id in (2,3) returning id, usuario_id`);
console.log("requerimientos borrados:", JSON.stringify(r.rows));
const p = await c.query(`delete from productos where id in (39607, 39608) returning id, nombre_comercial`);
console.log("productos creados por responder borrados:", JSON.stringify(p.rows));
const chk = await c.query(`select count(*)::int as n from requerimientos where id in (2,3)`);
console.log("restan:", chk.rows[0].n);
await c.end();
