import pg from "pg"; import dotenv from "dotenv"; dotenv.config();
const { Client } = pg;
const c = new Client({ host: process.env.SUPABASE_DB_HOST, port: process.env.SUPABASE_DB_PORT||5432, database: process.env.SUPABASE_DB_NAME||"postgres", user: process.env.SUPABASE_DB_USER, password: process.env.SUPABASE_DB_PASSWORD, ssl: { rejectUnauthorized:false } });
await c.connect();
const u = await c.query(`update productos set disponible = false where id = 38890 returning id, precio_usd, disponible`);
console.log("TRAMAL estado navegador:", JSON.stringify(u.rows[0]));
await c.query(`delete from ordenes where id = 32 and usuario_id = 4`);
const chk = await c.query(`select count(*)::int as n from ordenes where id = 32`);
console.log("orden 32 eliminada, restante:", chk.rows[0].n);
await c.end();
