import pg from "pg"; import dotenv from "dotenv"; dotenv.config();
const { Client } = pg;
const c = new Client({ host: process.env.SUPABASE_DB_HOST, port: process.env.SUPABASE_DB_PORT||5432, database: process.env.SUPABASE_DB_NAME||"postgres", user: process.env.SUPABASE_DB_USER, password: process.env.SUPABASE_DB_PASSWORD, ssl: { rejectUnauthorized:false } });
await c.connect();
const q = async (label, sql) => { const r = await c.query(sql); console.log("=== "+label+" ==="); console.log(JSON.stringify(r.rows,null,2)); };
await q("users columnas", `select column_name from information_schema.columns where table_name='users' and table_schema='public' order by ordinal_position`);
await q("users count", `select count(*)::int as n from users`);
await q("ordenes count", `select count(*)::int as n from ordenes`);
await q("ordenes por estado", `select estado, count(*)::int as n from ordenes group by estado order by n desc`);
await q("requerimientos count", `select count(*)::int as n from requerimientos`);
await q("products/stats endpoint? no - staff count", `select rol, count(*)::int as n from staff group by rol`);
await q("alertas de disponibilidad tablas", `select table_name from information_schema.tables where table_schema='public' and table_name ilike '%alerta%' or table_name ilike '%disponib%'`);
await c.end(); console.log("FIN");
