import pg from "pg"; import dotenv from "dotenv"; dotenv.config(); import fs from "fs";
const { Client } = pg;
const c = new Client({ host: process.env.SUPABASE_DB_HOST, port: process.env.SUPABASE_DB_PORT||5432, database: process.env.SUPABASE_DB_NAME||"postgres", user: process.env.SUPABASE_DB_USER, password: process.env.SUPABASE_DB_PASSWORD, ssl: { rejectUnauthorized:false } });
await c.connect();
await c.query(`ALTER TABLE staff DROP CONSTRAINT IF EXISTS staff_rol_check; ALTER TABLE staff ADD CONSTRAINT staff_rol_check CHECK (rol = ANY (ARRAY['vendedor','despachador','almacenista','contabilidad','administrador','director','admin']::text[]));`);
console.log("009 APLICADA");
const sql015 = fs.readFileSync("src/migrations/015_staff_auditoria.sql", "utf8");
await c.query(sql015);
console.log("015 APLICADA");
const chk = await c.query(`select conname, pg_get_constraintdef(oid) from pg_constraint where conrelid='staff'::regclass and contype='c' and conname='staff_rol_check'`);
console.log("check staff:", chk.rows[0].pg_get_constraintdef);
const st = await c.query(`select table_name from information_schema.columns where column_name='staff_id' and table_name in ('requerimientos','cotizaciones','solicitudes_documentos','promociones_plantillas') order by table_name`);
console.log("tablas con staff_id:", st.rows.map(r=>r.table_name).join(", "));
const pe = await c.query(`select count(*)::int as n from information_schema.tables where table_name='promociones_plantillas_eliminadas'`);
console.log("promociones_plantillas_eliminadas:", pe.rows[0].n ? "EXISTE" : "NO EXISTE");
await c.end();
